import { Navbar } from "@/components/layout/navbar";
import "@/app/globals.css";
import ContentDiv from "@/components/layout/contentDiv";
import { Noto_Sans as NotoSans } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const fontSans = NotoSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
